'use strict';
(()=>{
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const zones=[{name:'雨のスカイライン',sub:'SKYLINE',sky:'#102b40',glow:'#72ffe0',floor:'#1f4954'},{name:'灼熱の鋳造区',sub:'FOUNDRY',sky:'#302032',glow:'#ffab75',floor:'#563c49'},{name:'静寂の中枢',sub:'THE CORE',sky:'#201e42',glow:'#bcadff',floor:'#3c3766'}];
let W=960,H=540,cam=0,time=0,state='title',zone=0,score=0,best=0,player,enemies=[],bullets=[],shots=[],particles=[],drops=[],platforms=[],boss,checkpoint=80,checkpointScore=0,kills=0,shake=0,toastTimer=0,auto=true,muted=true,audio=null,fireTimer=0,stageTimer=0,seed=7;
const keys=new Set(),held=new Map();let jumpQueued=false,dashQueued=false;
try{best=Number(localStorage.getItem('neon-rift-best'))||0;}catch{}
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function tone(f=440,d=.07,type='square',vol=.025){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,f/2),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function initAudio(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function resize(){const r=canvas.getBoundingClientRect();H=540;W=clamp(540*r.width/r.height,380,1400);canvas.width=Math.round(W);canvas.height=H;}
new ResizeObserver(resize).observe(canvas);
function burst(x,y,color,n=18,power=180){for(let i=0;i<n;i++){const a=rand()*Math.PI*2,s=rand()*power;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+rand()*.5,max:.75,color,size:2+rand()*4});}if(particles.length>350)particles.splice(0,particles.length-350);}
function toast(t){$('toast').textContent=t;toastTimer=2.5;}
function setup(z,respawn=false){zone=z;seed=73+z;cam=0;time=0;enemies=[];bullets=[];shots=[];particles=[];drops=[];platforms=[];boss=null;stageTimer=0;fireTimer=0;const start=respawn?checkpoint:80;if(!respawn){checkpoint=80;checkpointScore=score;}
player={x:start,y:350,w:26,h:38,vx:0,vy:0,dir:1,jumps:0,ground:false,coyote:0,hp:$('difficulty').value==='casual'?8:5,maxHp:$('difficulty').value==='casual'?8:5,inv:2,dash:0,cool:0,weapon:0,weaponTime:0};
platforms.push({x:0,y:448,w:1260,h:100},{x:1380,y:448,w:1160,h:100},{x:2660,y:448,w:1700,h:100});
for(const p of [[380,352,160],[780,320,170],[1170,354,320],[1680,350,180],[2100,300,190],[2430,354,330],[2910,348,180],[3240,306,180]])platforms.push({x:p[0],y:p[1],w:p[2],h:16});
for(let i=0;i<19;i++){const x=530+i*150;if(x<start+220)continue;let drone=i%3===1;enemies.push({x,y:drone?250+(i%3)*25:412,w:drone?34:30,h:drone?26:36,hp:drone?3+z:4+z,baseY:250+(i%3)*25,type:drone?'drone':'walker',timer:1.2+(i%4)*.3,phase:i,dead:false});}
for(const x of [720,1600,2270,2960]){if(x>start)drops.push({x,y:390,w:24,h:24,type:'weapon',life:999});}for(const x of [1100,1970,3150])if(x>start)drops.push({x,y:395,w:24,h:24,type:'health',life:999});
$('stage').textContent=`0${z+1} / ${zones[z].name}`;$('bossbar').hidden=true;$('checkpoint').textContent=`CHECKPOINT ${start===80?'00':'01'}`;toast(respawn?'チェックポイントから再出撃':`0${z+1} / ${zones[z].sub}`);updateHud();}
function start(){initAudio();score=0;checkpoint=80;kills=0;setup(0);state='playing';document.body.classList.add('playing');$('pause').textContent='Ⅱ';clearInput();}
function clearInput(){keys.clear();held.clear();jumpQueued=false;dashQueued=false;document.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));}
function down(name){return keys.has(name)||[...held.values()].includes(name);}
function jump(){if(player.ground||player.coyote>0||player.jumps<2){player.vy=-440;player.jumps=player.ground||player.coyote>0?1:player.jumps+1;player.ground=false;player.coyote=0;tone(510,.09,'sine');burst(player.x+13,player.y+38,'#85ffe1',8,80);}}
function hurt(fall=false){if(!fall&&(player.inv>0||player.dash>0))return;player.hp--;player.inv=1.5;shake=9;tone(120,.18,'sawtooth',.045);burst(player.x+13,player.y+18,'#ff927e');if(fall){player.x=checkpoint;player.y=300;player.vy=0;cam=Math.max(0,player.x-W*.3);}if(player.hp<=0)finish(false);}
function finish(win){state=win?'win':'dead';clearInput();document.body.classList.remove('playing');$('overlay').querySelector('h1').innerHTML=win?'CITY<br><em>SAVED</em><span>都市を救った</span>':'SIGNAL<br><em>LOST</em><span>再接続を待っています</span>';$('description').innerHTML=win?'空中都市に、夜明けが戻った。<br>救援ミッション完了。': '信号が途切れた。もう一度、空へ。<br>チェックポイントから再挑戦できます。';$('start').innerHTML=win?'もう一度遊ぶ ↗':'再出撃する ↗';$('difficulty').hidden=true;best=Math.max(best,score);try{localStorage.setItem('neon-rift-best',String(best));}catch{}$('result').textContent=`SCORE ${score.toString().padStart(6,'0')} / BEST ${best.toString().padStart(6,'0')}`;}
function pause(){if(state==='playing'){state='paused';clearInput();$('pause').textContent='▶';toast('PAUSED — Ⅱ / P で再開');}else if(state==='paused'){state='playing';$('pause').textContent='Ⅱ';toast('再開');}}
function updateHud(){$('health').textContent='●'.repeat(Math.max(0,player.hp))+'○'.repeat(Math.max(0,player.maxHp-player.hp));$('score').textContent=String(score).padStart(6,'0');$('progress').style.width=`${Math.min(100,player.x/4140*100)}%`;$('weapon').textContent=['PULSE / 連射','FAN / 拡散弾','LANCE / 貫通弾'][player.weapon];$('dashstate').textContent=player.cool>0?`DASH ${player.cool.toFixed(1)}s`:'DASH READY';}
function shoot(){let angle=player.dir===1?0:Math.PI;const targets=enemies.filter(e=>!e.dead&&Math.abs(e.x-player.x)<500&&(e.x-player.x)*player.dir>-20);if(boss&&boss.hp>0)targets.push(boss);const t=targets.sort((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)-Math.hypot(b.x-player.x,b.y-player.y))[0];if(t&&Math.abs(t.x-player.x)<650)angle=Math.atan2(t.y+t.h/2-(player.y+16),t.x+t.w/2-(player.x+13));if(down('up'))angle=-Math.PI/2;
for(const spread of player.weapon===1?[-.19,0,.19]:[0]){let a=angle+spread;shots.push({x:player.x+13+Math.cos(a)*20,y:player.y+16+Math.sin(a)*20,w:player.weapon===2?24:12,h:5,vx:Math.cos(a)*790,vy:Math.sin(a)*790,life:1.1,power:player.weapon===2?3:1,pierce:player.weapon===2,hits:new Set()});}tone(player.weapon===2?290:700,.045,'square',.012);}
function enemyShoot(e,speed=170,offset=0){const a=Math.atan2(player.y+20-e.y-e.h/2,player.x+13-e.x-e.w/2)+offset;bullets.push({x:e.x+e.w/2,y:e.y+e.h/2,w:9,h:9,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:5});}
function damageEnemy(e,s){e.hp-=s.power;burst(s.x,s.y,'#e5fff7',4,75);if(e.hp<=0&&!e.dead){e.dead=true;score+=e===boss?1500:100;kills++;burst(e.x+e.w/2,e.y+e.h/2,'#ffb575',e===boss?65:22,230);shake=e===boss?15:3;tone(75,.2,'sawtooth',.03);if(e!==boss&&kills%6===0)drops.push({x:e.x,y:e.y,w:24,h:24,type:'health',life:15});if(e===boss){bullets=[];stageTimer=2.8;toast(zone===2?'CORE SHUTDOWN — 都市を解放':'AREA CLEAR');}}}
function update(dt){time+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').textContent='';}shake=Math.max(0,shake-dt*30);player.inv=Math.max(0,player.inv-dt);player.cool=Math.max(0,player.cool-dt);player.dash=Math.max(0,player.dash-dt);player.weaponTime-=dt;if(player.weaponTime<=0)player.weapon=0;
if(stageTimer>0){stageTimer-=dt;if(stageTimer<=0){score+=500;if(zone<2)setup(zone+1);else finish(true);}updateHud();return;}
if(jumpQueued){jump();jumpQueued=false;}if(dashQueued){if(player.cool<=0){player.dash=.2;player.cool=1.1;player.inv=Math.max(player.inv,.23);tone(180,.12,'sawtooth');}dashQueued=false;}
const move=Number(down('right'))-Number(down('left'));if(move)player.dir=move;player.vx=player.dash>0?player.dir*720:move*245;player.vy+=1250*dt;if(player.dash>0){player.vy=0;burst(player.x+13,player.y+20,'#74ffe0',2,35);}const oldY=player.y;player.x=clamp(player.x+player.vx*dt,boss&&boss.hp>0?3490:0,4180);player.y+=player.vy*dt;player.ground=false;for(const p of platforms){if(player.x+player.w>p.x&&player.x<p.x+p.w&&oldY+player.h<=p.y+2&&player.y+player.h>=p.y&&player.vy>=0){player.y=p.y-player.h;player.vy=0;player.ground=true;player.jumps=0;}}
player.coyote=player.ground?.1:Math.max(0,player.coyote-dt);if(player.y>590){hurt(true);if(state!=='playing')return;}
if(player.x>1850&&checkpoint<1800){checkpoint=1810;checkpointScore=score;player.hp=Math.min(player.maxHp,player.hp+2);$('checkpoint').textContent='CHECKPOINT 01';toast('CHECKPOINT — シールド回復');}
if(player.x>3450&&!boss){boss={x:3900,y:290,w:108,h:130,hp:100+zone*35,maxHp:100+zone*35,timer:1.4,phase:0,dead:false};$('bossbar').hidden=false;$('bossname').textContent=['WARDEN / 境界の守護機','CRUCIBLE / 炉心機','NULL CROWN / 中枢制御機'][zone];toast('WARNING — 巨大機接近');}
cam+=(clamp(player.x-W*.33,0,Math.max(0,4300-W))-cam)*Math.min(1,dt*8);
fireTimer-=dt;if((auto||down('fire'))&&fireTimer<=0){shoot();fireTimer=player.weapon===2?.15:.105;}
for(const e of enemies){if(e.dead||e.x<cam-100||e.x>cam+W+150)continue;e.timer-=dt;if(e.type==='drone')e.y=e.baseY+Math.sin(time*2+e.phase)*36;else {e.x+=Math.sin(time+e.phase)*22*dt;}if(e.timer<=0){enemyShoot(e,($('difficulty').value==='casual'?135:180)+zone*15);e.timer=2.1+rand();}if(hit(player,e))hurt();}
if(boss&&boss.hp>0){boss.y=290+Math.sin(time*1.4)*55;boss.timer-=dt;if(boss.timer<=0){boss.phase++;const count=boss.hp<boss.maxHp*.5?5:3;for(let i=0;i<count;i++)enemyShoot(boss,zone*20+155,(i-(count-1)/2)*.22);boss.timer=boss.hp<boss.maxHp*.5?.8:1.3;burst(boss.x+20,boss.y+65,'#ff896f',10,60);}if(hit(player,boss))hurt();$('bosshealth').style.width=`${Math.max(0,boss.hp/boss.maxHp*100)}%`;}
for(const s of shots){s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;for(const e of boss?[...enemies,boss]:enemies){if(e.dead||s.life<=0||s.hits.has(e))continue;if(hit(s,e)){damageEnemy(e,s);s.hits.add(e);if(!s.pierce)s.life=0;}}}
for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(hit(b,player)){hurt();b.life=0;}}
for(const d of drops){d.life-=dt;if(hit({x:d.x-8,y:d.y-8,w:40,h:40},player)){d.life=0;if(d.type==='health'){player.hp=Math.min(player.maxHp,player.hp+2);toast('SHIELD +2');}else{player.weapon=player.weapon===1?2:1;player.weaponTime=18;toast(player.weapon===1?'FAN — 拡散弾':'LANCE — 貫通弾');}tone(1000,.2,'sine');burst(d.x,d.y,'#8bffe1');score+=50;}}
shots=shots.filter(s=>s.life>0);bullets=bullets.filter(b=>b.life>0&&b.x>cam-200&&b.x<cam+W+300);drops=drops.filter(d=>d.life>0);enemies=enemies.filter(e=>!e.dead);for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;}particles=particles.filter(p=>p.life>0);updateHud();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function line(x,y,x2,y2,c,width=1){ctx.strokeStyle=c;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function background(){let z=zones[zone];const g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#081522');g.addColorStop(.65,z.sky);g.addColorStop(1,'#112734');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
const moonX=W*.75-cam*.03;circle(moonX,140,71,z.glow+'08');circle(moonX,140,53,z.glow+'0a');circle(moonX,140,37,'#a8d8cc18');
for(let layer=0;layer<3;layer++){let step=layer===0?100:145,par=.1+layer*.12;for(let i=-1;i<W/step+2;i++){let index=i+Math.floor(cam*par/step),x=i*step-(cam*par%step),h=65+((index*73+layer*43)%160+160)%160,y=420-h;rect(x,y,step-16,h,layer===0?'#17313e':layer===1?'#153440':'#173d49');rect(x+8,y+8,step-34,3,z.glow+'28');for(let row=0;row<7;row++)for(let col=0;col<3;col++){if((index+row+col)%3===0)rect(x+13+col*23,y+23+row*22,6,3,z.glow+'35');}if(index%3===0){line(x+30,y,x+30,y-35,'#365462');circle(x+30,y-36,2,z.glow);}}}
for(let i=0;i<30;i++){let x=(i*113-time*55-cam*.2)%(W+100);if(x<0)x+=W+100;let y=(i*79+time*120)%510;line(x,y,x-7,y+18,'#9cccc911');}
line(0,425,W,425,z.glow+'44');}
function drawPlayer(x,y,scale=1,hero=false){ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);if(!hero&&player.dir<0){ctx.translate(26,0);ctx.scale(-1,1);}if(!hero&&player.inv>0&&Math.floor(time*15)%2===0)ctx.globalAlpha=.5;const run=hero?0:Math.sin(time*18)*(Math.abs(player.vx)>0?5:0);rect(-6,13,9,20,'#3c6c77');rect(-8,19,4,12,'#b2ffe9');rect(2,14,22,18,'#6be4d2');rect(4,17,8,13,'#c5fff0');rect(13,16,9,16,'#2c838c');rect(2,3,21,15,'#d7efe6');rect(9,7,18,7,'#142a42');rect(12,9,15,3,'#8bffe1');rect(1,0,17,5,'#8abbb9');rect(3,31,8,9+run,'#315467');rect(16,31,8,9-run,'#40697c');rect(1,38+run,12,4,'#d0eee5');rect(15,38-run,12,4,'#d0eee5');rect(19,19,24,8,'#486575');rect(24,17,13,3,'#b7ddd5');rect(37,20,9,5,'#8bffe1');if(hero){rect(-9,30,7,13,'#69e9d3');rect(-9,43,7,9,'#69e9d355');}ctx.restore();}
function draw(){ctx.save();if(shake>0&&state==='playing')ctx.translate(Math.sin(time*91)*shake,Math.cos(time*81)*shake*.5);background();let z=zones[zone];ctx.save();ctx.translate(-cam,0);for(const p of platforms){if(p.x+p.w<cam||p.x>cam+W)continue;rect(p.x,p.y,p.w,p.h,z.floor);rect(p.x,p.y,p.w,3,z.glow);rect(p.x,p.y+5,p.w,4,'#091c28');for(let x=p.x+15;x<p.x+p.w;x+=45){rect(x,p.y+13,24,4,'#a6d9d11c');if(p.h>20){line(x,p.y+29,x+22,p.y+51,'#a5c8c224',2);rect(x,p.y+60,27,2,'#071b28');}}}
for(const x of [1260,2540]){rect(x,513,120,27,'#ff685533');for(let j=0;j<5;j++)circle(x+j*28,515+Math.sin(time*4+j)*7,3,'#ff9b75');}
for(const d of drops){let y=d.y+Math.sin(time*3+d.x)*5;circle(d.x+12,y+12,22,d.type==='health'?'#8bffe119':'#ffcc7e19');ctx.strokeStyle=d.type==='health'?'#8bffe1':'#ffcc7e';ctx.lineWidth=2;ctx.strokeRect(d.x,y,24,24);ctx.font='bold 16px Arial';ctx.fillStyle=ctx.strokeStyle;ctx.fillText(d.type==='health'?'+':'W',d.x+5,y+18);}
for(const e of enemies){if(e.x<cam-100||e.x>cam+W+100)continue;if(e.type==='drone'){circle(e.x+17,e.y+13,24,'#ff926c10');rect(e.x,e.y+7,34,16,'#987777');rect(e.x+8,e.y,18,26,'#bfaaa0');rect(e.x+12,e.y+10,12,5,'#ff765f');line(e.x-8,e.y+2,e.x+42,e.y+2,'#66939c',3);circle(e.x+9,e.y+29,3,'#ffaf78');circle(e.x+25,e.y+29,3,'#ffaf78');}else{rect(e.x+3,e.y+7,25,23,'#997f80');rect(e.x+7,e.y,21,13,'#c5b5a5');rect(e.x+3,e.y+4,13,4,'#ff7a69');rect(e.x-8,e.y+15,20,7,'#d2a088');rect(e.x+3,e.y+29,7,7,'#506c7e');rect(e.x+21,e.y+29,7,7,'#506c7e');}}
if(boss&&boss.hp>0){const b=boss;circle(b.x+54,b.y+65,91,z.glow+'0c');ctx.save();ctx.translate(b.x+54,b.y+65);ctx.rotate(time*.3);ctx.strokeStyle=z.glow+'55';ctx.lineWidth=3;ctx.strokeRect(-68,-68,136,136);ctx.restore();rect(b.x+19,b.y,70,130,'#738492');rect(b.x,b.y+28,108,75,'#354b62');rect(b.x+9,b.y+38,90,55,'#192c42');circle(b.x+54,b.y+65,26,'#f88a76');circle(b.x+54,b.y+65,16,'#ffdcc0');circle(b.x+54,b.y+65,8,'#fff5df');rect(b.x-19,b.y+44,36,13,'#b4a49c');rect(b.x-19,b.y+78,36,13,'#b4a49c');for(let i=0;i<4;i++)rect(b.x+27+i*15,b.y+10,7,10,z.glow);}
for(const s of shots){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.atan2(s.vy,s.vx));rect(-10,-4,s.pierce?32:20,9,'#8bffe130');rect(-8,-2,s.pierce?27:16,4,'#c0ffec');ctx.restore();}for(const b of bullets){circle(b.x+4,b.y+4,9,'#ff786b25');circle(b.x+4,b.y+4,5,'#ff9275');circle(b.x+4,b.y+4,2,'#ffe8cb');}
if(player)drawPlayer(player.x,player.y);for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(p.x,p.y,p.size,p.size,p.color);}ctx.globalAlpha=1;ctx.restore();if(state==='title'){drawPlayer(W*.73,270,3.8,true);line(W*.67,455,W*.91,455,'#8bffe144',2);ctx.font='10px Arial';ctx.fillStyle='#8ba9b5';ctx.fillText('RIO / RESCUE UNIT 07',W*.65,483);}if(state==='paused'){rect(0,0,W,H,'#06111c88');ctx.font='bold 30px Arial';ctx.fillStyle='#c9fff1';ctx.textAlign='center';ctx.fillText('PAUSED',W/2,H/2);ctx.textAlign='left';}ctx.restore();}
const map={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyZ:'fire',KeyJ:'fire'};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName)&&state!=='playing'&&state!=='paused')return;if(map[e.code]||['Space','KeyW','ShiftLeft','ShiftRight','KeyX','KeyP','Escape'].includes(e.code))e.preventDefault();if(map[e.code])keys.add(map[e.code]);if(!e.repeat){if(e.code==='Space'||e.code==='KeyW')jumpQueued=true;if(['ShiftLeft','ShiftRight','KeyX'].includes(e.code))dashQueued=true;if(e.code==='KeyP'||e.code==='Escape')pause();}});
window.addEventListener('keyup',e=>{if(map[e.code])keys.delete(map[e.code]);});
for(const el of document.querySelectorAll('[data-hold],#jump,#dash')){el.addEventListener('pointerdown',e=>{e.preventDefault();if(state!=='playing')return;el.setPointerCapture(e.pointerId);el.classList.add('pressed');if(el.dataset.hold)held.set(e.pointerId,el.dataset.hold);if(el.id==='jump')jumpQueued=true;if(el.id==='dash')dashQueued=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,e=>{held.delete(e.pointerId);el.classList.remove('pressed');});}
window.addEventListener('blur',()=>{clearInput();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});$('pause').onclick=pause;$('start').onclick=()=>{if(state==='dead'){score=checkpointScore;setup(zone,true);state='playing';document.body.classList.add('playing');clearInput();}else start();$('start').blur();};$('sound').onclick=()=>{initAudio();muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';tone(660,.1,'sine');};$('auto').onchange=e=>auto=e.target.checked;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('app').requestFullscreen)await $('app').requestFullscreen();else toast('このブラウザでは端末を横向きにしてください');}catch{toast('端末を横向きにすると広く遊べます');}};
setup(0);$('toast').textContent='';toastTimer=0;let last=performance.now(),acc=0;function loop(now){const elapsed=Math.min(.08,(now-last)/1000);last=now;if(state==='playing'){acc+=elapsed;while(acc>=1/120&&state==='playing'){update(1/120);acc-=1/120;}}else{acc=0;if(state==='title')time+=elapsed;}draw();requestAnimationFrame(loop);}requestAnimationFrame(loop);
})();
