'use strict';
(()=>{
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
const zones=[
 {name:'雨のスカイライン',sub:'SKYLINE',sky:'#102b40',glow:'#72ffe0',floor:'#1f4954'},
 {name:'灼熱の鋳造区',sub:'FOUNDRY',sky:'#302032',glow:'#ffab75',floor:'#563c49'},
 {name:'静寂の中枢',sub:'THE CORE',sky:'#201e42',glow:'#bcadff',floor:'#3c3766'}
];
const frames={
 player_idle:[0,0,48,56],player_run:[48,0,48,56],player_jump:[96,0,48,56],player_dash:[144,0,64,56],player_hurt:[208,0,48,56],
 walker0:[0,64,48,56],walker1:[48,64,48,56],walker2:[96,64,48,56],drone0:[160,64,56,48],drone1:[208,64,56,48],drone2:[256,64,56,48],
 boss0:[0,128,160,150],boss1:[168,128,160,150],boss2:[336,128,160,150],
 health:[0,286,40,40],weapon:[40,286,40,40],pulse:[80,286,56,28],fan:[136,286,64,36],lance:[200,286,72,36],enemy_bullet:[272,286,48,36],spark:[320,286,48,40],explosion:[368,286,80,56],
 floor0:[0,352,144,48],hazard0:[152,352,144,48],prop0:[304,352,80,48],floor1:[0,404,144,48],hazard1:[152,404,144,48],prop1:[304,404,80,48],floor2:[0,456,144,48],hazard2:[152,456,144,48],prop2:[304,456,80,48]
};
const stageLayouts=[
 {grounds:[[0,1260],[1380,2540],[2660,4360]],ledges:[[380,352,160],[780,320,170],[1170,354,320],[1680,350,180],[2100,300,190],[2430,354,330],[2910,348,180],[3240,306,180]],
  enemies:[[530,'walker'],[680,'drone'],[830,'walker'],[980,'walker'],[1130,'drone'],[1450,'walker'],[1600,'drone'],[1750,'walker'],[2050,'walker'],[2200,'drone'],[2380,'walker'],[2740,'drone'],[2890,'walker'],[3050,'walker'],[3210,'drone'],[3370,'walker']],
  pickups:[[720,'weapon',1],[1100,'health'],[1600,'weapon',2],[1970,'health'],[2270,'weapon',1],[2960,'weapon',2],[3150,'health']]},
 {grounds:[[0,980],[1100,2080],[2220,3180],[3320,4360]],ledges:[[280,360,180],[620,310,140],[1220,335,200],[1570,285,160],[1900,360,180],[2380,320,220],[2820,270,160],[3150,350,180]],
  enemies:[[460,'walker'],[610,'walker'],[760,'drone'],[1180,'walker'],[1330,'walker'],[1490,'drone'],[1690,'walker'],[1880,'walker'],[2290,'walker'],[2440,'drone'],[2600,'walker'],[2790,'walker'],[2940,'drone'],[3090,'walker'],[3370,'walker'],[3510,'drone']],
  pickups:[[650,'weapon',2],[1260,'health'],[1710,'weapon',1],[2460,'health'],[2860,'weapon',2],[3370,'health']]},
 {grounds:[[0,860],[970,1680],[1810,2470],[2590,3290],[3410,4360]],ledges:[[250,300,160],[520,360,140],[1050,310,220],[1450,250,160],[1880,340,200],[2240,280,180],[2720,340,150],[3050,250,200],[3350,330,100]],
  enemies:[[420,'drone'],[610,'walker'],[760,'drone'],[1040,'drone'],[1210,'walker'],[1390,'drone'],[1580,'walker'],[1880,'drone'],[2050,'drone'],[2250,'walker'],[2630,'drone'],[2790,'walker'],[2960,'drone'],[3150,'drone'],[3380,'walker'],[3510,'drone']],
  pickups:[[560,'weapon',1],[1180,'health'],[1510,'weapon',2],[2070,'health'],[2760,'weapon',2],[3150,'health']]}
];
const BOSS_TRIGGER=3450,LEVEL_END=4360,CHECKPOINT_X=1850;
const atlas=new Image(),bgArt=new Image();let atlasReady=false,bgReady=false;
atlas.onload=()=>atlasReady=true;bgArt.onload=()=>bgReady=true;
atlas.src='assets/retro_atlas.png?v=7';bgArt.src='assets/retro_bg.png?v=7';
let W=960,H=540,cam=0,time=0,state='title',zone=0,score=0,best=0,player,enemies=[],bullets=[],shots=[],particles=[],drops=[],platforms=[],hazards=[],boss=null;
let checkpoint=80,checkpointScore=0,checkpointKills=0,checkpointActive=false,kills=0,shake=0,toastTimer=0,auto=true,muted=false,audio=null,fireTimer=0,stageTimer=0,clearFxTimer=0,bossDeath=null,seed=7,arenaActive=false;
const arena={left:3380,right:4260};
const keys=new Set(),held=new Map();let jumpQueued=false,dashQueued=false;
try{best=Number(localStorage.getItem('neon-rift-best'))||0;}catch{}
function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function tone(f=440,d=.07,type='square',vol=.025){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,f/2),audio.currentTime+d);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d);}
function initAudio(){try{if(!audio)audio=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
function resize(){const r=canvas.getBoundingClientRect();H=540;W=clamp(540*r.width/r.height,380,1400);canvas.width=Math.round(W);canvas.height=H;ctx.imageSmoothingEnabled=false;}
new ResizeObserver(resize).observe(canvas);
function burst(x,y,color,n=18,power=180){for(let i=0;i<n;i++){const a=rand()*Math.PI*2,s=rand()*power;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+rand()*.5,max:.75,color,size:2+rand()*4});}if(particles.length>350)particles.splice(0,particles.length-350);}
function updateParticles(dt){for(const p of particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;}particles=particles.filter(p=>p.life>0);}
function toast(t){$('toast').textContent=t;toastTimer=2.5;}
function buildStage(z){const L=stageLayouts[z];platforms=[];hazards=[];for(const [a,b] of L.grounds)platforms.push({x:a,y:448,w:b-a,h:100,ground:true});for(let i=0;i<L.grounds.length-1;i++){const a=L.grounds[i][1],b=L.grounds[i+1][0];if(b>a)hazards.push({x:a,w:b-a});}for(const p of L.ledges)platforms.push({x:p[0],y:p[1],w:p[2],h:16});}
function setup(z,respawn=false){zone=z;seed=73+z;cam=0;time=0;enemies=[];bullets=[];shots=[];particles=[];drops=[];boss=null;bossDeath=null;arenaActive=false;stageTimer=0;clearFxTimer=0;fireTimer=0;buildStage(z);const L=stageLayouts[z],start=respawn?checkpoint:80;if(!respawn){checkpoint=80;checkpointScore=score;checkpointKills=0;checkpointActive=false;kills=0;}else{kills=checkpointKills;checkpointActive=true;}
player={x:start,y:350,w:26,h:38,vx:0,vy:0,dir:1,jumps:0,ground:false,coyote:0,hp:$('difficulty').value==='casual'?8:5,maxHp:$('difficulty').value==='casual'?8:5,inv:2,dash:0,cool:0,weapon:0,weaponTime:0};
for(const [x,type] of L.enemies){if(x<start+220)continue;const drone=type==='drone';enemies.push({x,y:drone?245+(x%3)*18:412,w:drone?34:30,h:drone?26:36,hp:drone?3+z:4+z,baseY:drone?245+(x%3)*18:412,type,timer:1.1+rand()*.8,phase:rand()*6.28,dead:false,dir:-1});}
for(const [x,type,weapon] of L.pickups){if(x<=start)continue;drops.push({x,y:type==='health'?395:390,w:24,h:24,type,weapon:weapon||0,life:999});}
$('stage').textContent=`0${z+1} / ${zones[z].name}`;$('edition-zone').textContent=`0${z+1} / ${zones[z].sub}`;$('bossbar').hidden=true;$('checkpoint').textContent=`CHECKPOINT ${checkpointActive?'01':'00'}`;toast(respawn?'チェックポイントから再出撃':`0${z+1} / ${zones[z].sub}`);updateHud();}
function start(){initAudio();score=0;checkpoint=80;checkpointScore=0;checkpointKills=0;kills=0;$('difficulty').hidden=false;setup(0);state='playing';document.body.classList.add('playing');$('pause').textContent='Ⅱ';clearInput();}
function clearInput(){keys.clear();held.clear();jumpQueued=false;dashQueued=false;document.querySelectorAll('.pressed').forEach(e=>e.classList.remove('pressed'));}
function down(name){return keys.has(name)||[...held.values()].includes(name);}
function jump(){if(player.ground||player.coyote>0||player.jumps<2){player.vy=-440;player.jumps=player.ground||player.coyote>0?1:player.jumps+1;player.ground=false;player.coyote=0;tone(510,.09,'sine');burst(player.x+13,player.y+38,'#85ffe1',8,80);}}
function hurt(fall=false){if(!fall&&(player.inv>0||player.dash>0))return;player.hp--;player.inv=1.5;shake=9;tone(120,.18,'sawtooth',.045);burst(player.x+13,player.y+18,'#ff927e');if(fall){player.x=checkpoint;player.y=300;player.vy=0;cam=Math.max(0,player.x-W*.45);}if(player.hp<=0)finish(false);}
function finish(win){state=win?'win':'dead';clearInput();document.body.classList.remove('playing');$('overlay').querySelector('h1').innerHTML=win?'CITY<br><em>SAVED</em><span>都市を救った</span>':'SIGNAL<br><em>LOST</em><span>再接続を待っています</span>';$('description').innerHTML=win?'空中都市に、夜明けが戻った。<br>救援ミッション完了。':'信号が途切れた。もう一度、空へ。<br>チェックポイントから再挑戦できます。';$('start').innerHTML=win?'もう一度遊ぶ ↗':'再出撃する ↗';$('difficulty').hidden=false;best=Math.max(best,score);try{localStorage.setItem('neon-rift-best',String(best));}catch{}$('result').textContent=`SCORE ${score.toString().padStart(6,'0')} / BEST ${best.toString().padStart(6,'0')}`;}
function pause(){if(state==='playing'){state='paused';clearInput();$('pause').textContent='▶';toast('PAUSED — Ⅱ / P で再開');}else if(state==='paused'){state='playing';$('pause').textContent='Ⅱ';toast('再開');}}
function stageProgress(){if(stageTimer>0)return 100;if(boss&&boss.hp>0)return 95+5*(1-boss.hp/boss.maxHp);return Math.min(95,player.x/BOSS_TRIGGER*95);}
function updateHud(){$('health').textContent='●'.repeat(Math.max(0,player.hp))+'○'.repeat(Math.max(0,player.maxHp-player.hp));$('score').textContent=String(score).padStart(6,'0');$('progress').style.width=`${stageProgress()}%`;const names=['PULSE / 連射','FAN / 拡散弾','LANCE / 貫通弾'];$('weapon').textContent=player.weapon?`${names[player.weapon]}  ${Math.max(0,Math.ceil(player.weaponTime))}s`:names[0];$('dashstate').textContent=player.cool>0?`DASH ${player.cool.toFixed(1)}s`:'DASH READY';}
function pointInRect(x,y,r){return x>=r.x&&x<=r.x+r.w&&y>=r.y&&y<=r.y+r.h;}
function segmentRectHit(x1,y1,x2,y2,r,pad=0){const q={x:r.x-pad,y:r.y-pad,w:r.w+pad*2,h:r.h+pad*2};if(pointInRect(x1,y1,q)||pointInRect(x2,y2,q))return true;const dx=x2-x1,dy=y2-y1;let t0=0,t1=1;for(const [p,v] of [[-dx,x1-q.x],[dx,q.x+q.w-x1],[-dy,y1-q.y],[dy,q.y+q.h-y1]]){if(p===0){if(v<0)return false;continue;}const t=v/p;if(p<0){if(t>t1)return false;if(t>t0)t0=t;}else{if(t<t0)return false;if(t<t1)t1=t;}}return true;}
function terrainBlocks(x1,y1,x2,y2,pad=0){for(const p of platforms)if(segmentRectHit(x1,y1,x2,y2,p,pad))return true;return false;}
function visibleOnScreen(e,margin=30){return e.x+e.w>cam-margin&&e.x<cam+W+margin;}
function acquireTarget(){const mx=player.x+player.w/2,my=player.y+16,maxRange=Math.min(520,W*.78),cosLimit=Math.cos(Math.PI/3);const list=enemies.filter(e=>!e.dead);if(boss&&boss.hp>0)list.push(boss);let bestTarget=null,bestD=Infinity;for(const e of list){if(!visibleOnScreen(e,30))continue;const tx=e.x+e.w/2,ty=e.y+e.h/2,dx=tx-mx,dy=ty-my,d=Math.hypot(dx,dy);if(d>maxRange||dx*player.dir<=0)continue;if((dx*player.dir)/Math.max(1,d)<cosLimit)continue;if(terrainBlocks(mx,my,tx,ty,2))continue;if(d<bestD){bestD=d;bestTarget=e;}}return bestTarget;}
function shoot(manual=false){let angle=player.dir===1?0:Math.PI,target=null;if(manual&&down('up'))angle=-Math.PI/2;else{target=acquireTarget();if(target){angle=Math.atan2(target.y+target.h/2-(player.y+16),target.x+target.w/2-(player.x+player.w/2));}else if(!manual)return false;}
const muzzleX=player.x+player.w/2+(down('up')?0:player.dir*17),muzzleY=player.y+16;for(const spread of player.weapon===1?[-.19,0,.19]:[0]){const a=angle+spread,kind=player.weapon;shots.push({x:muzzleX,y:muzzleY,px:muzzleX,py:muzzleY,vx:Math.cos(a)*790,vy:Math.sin(a)*790,life:1.1,power:kind===2?3:1,pierce:kind===2,kind,radius:kind===1?5:3,length:kind===2?36:kind===1?26:18,hits:new Set()});}tone(player.weapon===2?290:700,.045,'square',.012);return true;}
function enemyShootAngle(e,angle,speed=170){const dir=Math.cos(angle)>=0?1:-1,x=e.x+e.w/2+dir*(e.w/2+3),y=e.y+e.h*.5;bullets.push({x,y,px:x,py:y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life:5,radius:5});}
function enemyShoot(e,speed=170,offset=0){const tx=player.x+player.w/2,ty=player.y+20,sx=e.x+e.w/2,sy=e.y+e.h/2,a=Math.atan2(ty-sy,tx-sx)+offset;enemyShootAngle(e,a,speed);}
function damageEnemy(e,s){e.hp-=s.power;burst(s.x,s.y,'#e5fff7',4,75);if(e.hp<=0&&!e.dead){e.dead=true;e.hp=0;score+=e===boss?1500:100;kills++;burst(e.x+e.w/2,e.y+e.h/2,'#ffb575',e===boss?65:22,230);shake=e===boss?15:3;tone(75,.2,'sawtooth',.03);if(e!==boss&&kills%6===0)drops.push({x:e.x,y:e.y,w:24,h:24,type:'health',weapon:0,life:15});if(e===boss){bullets=[];shots=[];stageTimer=2.8;clearFxTimer=0;bossDeath={x:e.x+e.w/2,y:e.y+e.h/2};arenaActive=false;toast(zone===2?'CORE SHUTDOWN — 都市を解放':'AREA CLEAR');}}}
function spawnBoss(){boss={x:3975,y:290,w:108,h:130,hp:100+zone*35,maxHp:100+zone*35,timer:1.1,phase:0,dead:false,dir:-1};arenaActive=true;$('bossbar').hidden=false;$('bossname').textContent=['WARDEN / 境界の守護機','CRUCIBLE / 炉心機','NULL CROWN / 中枢制御機'][zone];toast('WARNING — ARENA LOCK');}
function updateBoss(dt){if(!boss||boss.hp<=0)return;boss.dir=player.x<boss.x?-1:1;if(!visibleOnScreen(boss,20)){boss.timer=Math.max(boss.timer,.2);return;}boss.timer-=dt;if(zone===0)boss.y=290+Math.sin(time*1.4)*55;else if(zone===1)boss.y=318+Math.sin(time*.85)*24;else boss.y=270+Math.sin(time*2.2)*78;if(boss.timer>0)return;boss.phase++;
const low=boss.hp<boss.maxHp*.5;if(zone===0){const count=low?5:3;for(let i=0;i<count;i++)enemyShoot(boss,170+(low?25:0),(i-(count-1)/2)*.22);boss.timer=low?.82:1.25;}
else if(zone===1){if(boss.phase%2){for(const o of [-.10,.10])enemyShoot(boss,215,o);}else{for(const o of [-.48,-.24,0,.24,.48])enemyShoot(boss,155,o);if(low)enemyShootAngle({x:boss.x,y:405,w:boss.w,h:20},Math.PI,235);}boss.timer=low?.78:1.08;}
else{if(boss.phase%2){const n=low?12:8;for(let i=0;i<n;i++)enemyShootAngle(boss,Math.PI*2*i/n,145+(low?25:0));}else{for(const o of [-.15,0,.15])enemyShoot(boss,230,o);}boss.timer=low?.65:.92;}
burst(boss.x+20,boss.y+65,'#ff896f',10,60);}
function updateStageClear(dt){updateParticles(dt);shake=Math.max(0,shake-dt*30);clearFxTimer-=dt;if(bossDeath&&clearFxTimer<=0){clearFxTimer=.18;burst(bossDeath.x+(rand()-.5)*100,bossDeath.y+(rand()-.5)*90,'#ffb575',10,140);}stageTimer-=dt;updateHud();if(stageTimer<=0){score+=500;if(zone<2)setup(zone+1);else finish(true);}}
function update(dt){time+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').textContent='';}if(stageTimer>0){updateStageClear(dt);return;}shake=Math.max(0,shake-dt*30);player.inv=Math.max(0,player.inv-dt);player.cool=Math.max(0,player.cool-dt);player.dash=Math.max(0,player.dash-dt);player.weaponTime-=dt;if(player.weaponTime<=0){player.weapon=0;player.weaponTime=0;}if(jumpQueued){jump();jumpQueued=false;}if(dashQueued){if(player.cool<=0){player.dash=.2;player.cool=1.1;player.inv=Math.max(player.inv,.23);tone(180,.12,'sawtooth');}dashQueued=false;}
const move=Number(down('right'))-Number(down('left'));if(move)player.dir=move;player.vx=player.dash>0?player.dir*720:move*245;player.vy+=1250*dt;if(player.dash>0){player.vy=0;burst(player.x+13,player.y+20,'#74ffe0',2,35);}const oldY=player.y;let minX=0,maxX=LEVEL_END-player.w;if(arenaActive&&boss&&boss.hp>0){minX=arena.left+18;maxX=Math.min(arena.right-player.w-18,boss.x-player.w-12);}player.x=clamp(player.x+player.vx*dt,minX,maxX);player.y+=player.vy*dt;player.ground=false;for(const p of platforms){if(player.x+player.w>p.x&&player.x<p.x+p.w&&oldY+player.h<=p.y+2&&player.y+player.h>=p.y&&player.vy>=0){player.y=p.y-player.h;player.vy=0;player.ground=true;player.jumps=0;}}player.coyote=player.ground?.1:Math.max(0,player.coyote-dt);if(player.y>590){hurt(true);if(state!=='playing')return;}
if(player.x>CHECKPOINT_X&&!checkpointActive){checkpoint=1810;checkpointScore=score;checkpointKills=kills;checkpointActive=true;player.hp=Math.min(player.maxHp,player.hp+2);$('checkpoint').textContent='CHECKPOINT 01';toast('CHECKPOINT — シールド回復');}if(player.x>BOSS_TRIGGER&&!boss)spawnBoss();
let targetCam=clamp(player.x-W*(player.dir>0?.30:.70),0,Math.max(0,LEVEL_END-W));cam+=(targetCam-cam)*Math.min(1,dt*7);
fireTimer-=dt;if(fireTimer<=0){const manual=down('fire'),fired=manual?shoot(true):auto?shoot(false):false;if(fired)fireTimer=player.weapon===2?.15:.105;}
for(const e of enemies){if(e.dead||!visibleOnScreen(e,45))continue;e.dir=player.x>=e.x?1:-1;e.timer-=dt;if(e.type==='drone'){const freq=zone===2?3.0:zone===1?1.55:2.0,amp=zone===2?44:zone===1?20:32;e.y=e.baseY+Math.sin(time*freq+e.phase)*amp;}else{const freq=zone===1?1.45:zone===2?.8:1,pace=zone===1?28:zone===2?13:18;e.x+=Math.sin(time*freq+e.phase)*pace*dt;}if(e.timer<=0){const sx=e.x+e.w/2,sy=e.y+e.h/2,tx=player.x+player.w/2,ty=player.y+20;if(!terrainBlocks(sx,sy,tx,ty,3)){const base=($('difficulty').value==='casual'?135:180)+zone*15;if(zone===0)enemyShoot(e,base);else if(zone===1){if(e.type==='walker'){enemyShoot(e,base,-.07);enemyShoot(e,base,.07);}else enemyShoot(e,base+10);}else{if(e.type==='drone'){enemyShoot(e,base+20,-.11);enemyShoot(e,base+20,.11);}else enemyShoot(e,base+25);}}e.timer=(zone===2?1.65:zone===1?1.85:2.0)+rand()*.8;}if(hit(player,e))hurt();}
updateBoss(dt);if(boss&&boss.hp>0&&hit(player,boss))hurt();if(boss&&boss.hp>0)$('bosshealth').style.width=`${Math.max(0,boss.hp/boss.maxHp*100)}%`;
for(const s of shots){s.px=s.x;s.py=s.y;s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt;if(s.life<=0)continue;if(terrainBlocks(s.px,s.py,s.x,s.y,s.radius)){s.life=0;burst(s.x,s.y,'#e5fff7',3,45);continue;}const targets=boss?[...enemies,boss]:enemies;for(const e of targets){if(e.dead||s.life<=0||s.hits.has(e))continue;if(segmentRectHit(s.px,s.py,s.x,s.y,e,s.radius)){damageEnemy(e,s);s.hits.add(e);if(!s.pierce)s.life=0;}}}
for(const b of bullets){b.px=b.x;b.py=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(b.life<=0)continue;if(terrainBlocks(b.px,b.py,b.x,b.y,b.radius)){b.life=0;burst(b.x,b.y,'#ff927e',3,45);continue;}if(segmentRectHit(b.px,b.py,b.x,b.y,player,b.radius)){hurt();b.life=0;}}
for(const d of drops){d.life-=dt;if(hit({x:d.x-8,y:d.y-8,w:40,h:40},player)){d.life=0;if(d.type==='health'){player.hp=Math.min(player.maxHp,player.hp+2);toast('SHIELD +2');}else{player.weapon=d.weapon||1;player.weaponTime=18;toast(player.weapon===1?'FAN — 拡散弾 18s':'LANCE — 貫通弾 18s');}tone(1000,.2,'sine');burst(d.x,d.y,'#8bffe1');score+=50;}}
shots=shots.filter(s=>s.life>0&&s.x>cam-250&&s.x<cam+W+250&&s.y>-100&&s.y<640);bullets=bullets.filter(b=>b.life>0&&b.x>cam-150&&b.x<cam+W+150&&b.y>-100&&b.y<640);drops=drops.filter(d=>d.life>0);enemies=enemies.filter(e=>!e.dead);updateParticles(dt);updateHud();}
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function line(x,y,x2,y2,c,width=1){ctx.strokeStyle=c;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}function circle(x,y,r,c){ctx.fillStyle=c;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}
function sprite(name,x,y,w,h,flip=false,alpha=1){const f=frames[name];if(!atlasReady||!f)return false;ctx.save();ctx.globalAlpha*=alpha;ctx.imageSmoothingEnabled=false;if(flip){ctx.translate(Math.round(x+w),Math.round(y));ctx.scale(-1,1);ctx.drawImage(atlas,f[0],f[1],f[2],f[3],0,0,Math.round(w),Math.round(h));}else ctx.drawImage(atlas,f[0],f[1],f[2],f[3],Math.round(x),Math.round(y),Math.round(w),Math.round(h));ctx.restore();return true;}
function background(){if(bgReady){ctx.imageSmoothingEnabled=false;const tileW=960,tileH=540,off=-((cam*.055)%tileW);for(let x=off-tileW;x<W+tileW;x+=tileW)ctx.drawImage(bgArt,0,zone*180,320,180,Math.round(x),0,tileW,tileH);rect(0,0,W,H,'#02081422');return;}const z=zones[zone],g=ctx.createLinearGradient(0,0,0,540);g.addColorStop(0,'#081522');g.addColorStop(.65,z.sky);g.addColorStop(1,'#112734');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);}
function drawPlayer(x,y,scale=1,hero=false){let name='player_idle';if(!hero){if(player.inv>.9)name='player_hurt';else if(player.dash>0)name='player_dash';else if(!player.ground)name='player_jump';else if(Math.abs(player.vx)>1)name='player_run';}const dw=(name==='player_dash'?54:42)*scale,dh=52*scale,dx=x-8*scale,dy=y-(hero?10:12)*scale;if(sprite(name,dx,dy,dw,dh,!hero&&player.dir<0,!hero&&player.inv>0&&Math.floor(time*15)%2===0?.45:1))return;rect(x,y,26*scale,38*scale,'#6be4d2');}
function drawPlatform(p){const key=`floor${zone}`,tile=144;for(let x=p.x;x<p.x+p.w;x+=tile){const w=Math.min(tile,p.x+p.w-x);if(!sprite(key,x,p.y,w,p.h))rect(x,p.y,w,p.h,zones[zone].floor);}}
function drawGate(x,active){const y=305;for(let yy=y;yy<448;yy+=46)sprite(`prop${zone}`,x-20,yy,40,46,false,active?1:.35);line(x,305,x,448,active?zones[zone].glow:'#46616b',active?4:2);if(active){for(let i=0;i<6;i++)line(x-8,318+i*20,x+8,318+i*20,zones[zone].glow,1);}}
function drawCheckpoint(){const x=CHECKPOINT_X-20,y=386;sprite(`prop${zone}`,x,y,56,58,false,1);line(CHECKPOINT_X+8,372,CHECKPOINT_X+8,448,checkpointActive?zones[zone].glow:'#607782',3);if(checkpointActive)circle(CHECKPOINT_X+8,379,6,zones[zone].glow);}
function drawPickup(d,y){if(d.type==='health'){if(!sprite('health',d.x-7,y-7,38,38))circle(d.x+12,y+12,18,'#8bffe155');return;}if(!sprite('weapon',d.x-7,y-7,38,38))circle(d.x+12,y+12,18,'#ffcc7e55');const key=d.weapon===2?'lance':'fan';sprite(key,d.x+3,y+3,d.weapon===2?22:18,10);}
function draw(){ctx.save();ctx.imageSmoothingEnabled=false;if(shake>0&&state==='playing')ctx.translate(Math.sin(time*91)*shake,Math.cos(time*81)*shake*.5);background();ctx.save();ctx.translate(-cam,0);
for(const p of platforms){if(p.x+p.w<cam||p.x>cam+W)continue;drawPlatform(p);}for(const h of hazards){if(!sprite(`hazard${zone}`,h.x,500,h.w,40))rect(h.x,513,h.w,27,'#ff685566');}drawCheckpoint();if(boss){drawGate(arena.left,arenaActive);drawGate(arena.right,arenaActive);}
for(const d of drops){const y=d.y+Math.sin(time*3+d.x)*5;drawPickup(d,y);}for(const e of enemies){if(!visibleOnScreen(e,100))continue;if(e.type==='drone'){if(!sprite(`drone${zone}`,e.x-11,e.y-10,56,48,e.dir<0))rect(e.x,e.y,34,26,'#bfaaa0');}else if(!sprite(`walker${zone}`,e.x-9,e.y-14,48,56,e.dir<0))rect(e.x,e.y,30,36,'#997f80');}
if(boss&&boss.hp>0){if(!sprite(`boss${zone}`,boss.x-26,boss.y-10,160,150,boss.dir<0))rect(boss.x,boss.y,108,130,'#738492');}
for(const s of shots){ctx.save();ctx.translate(s.x,s.y);ctx.rotate(Math.atan2(s.vy,s.vx));const key=s.kind===2?'lance':s.kind===1?'fan':'pulse',w=s.kind===2?42:s.kind===1?30:26,h=s.kind===1?18:14;if(!sprite(key,-w/2,-h/2,w,h))rect(-s.length/2,-2,s.length,4,'#c0ffec');ctx.restore();}for(const b of bullets){if(!sprite('enemy_bullet',b.x-13,b.y-10,26,20))circle(b.x,b.y,5,'#ff9275');}
if(player)drawPlayer(player.x,player.y);for(const p of particles){const a=clamp(p.life/p.max,0,1),sz=Math.max(5,p.size*2);if(!sprite(p.color==='#ffb575'?'explosion':'spark',p.x-sz,p.y-sz*.75,sz*2,sz*1.5,false,a)){ctx.globalAlpha=a;rect(p.x,p.y,p.size,p.size,p.color);ctx.globalAlpha=1;}}ctx.restore();
if(state==='title'){drawPlayer(W*.61,255,3.2,true);ctx.font='10px monospace';ctx.fillStyle='#8ba9b5';ctx.fillText('RIO / RESCUE UNIT 07',W*.65,483);}if(state==='paused'){rect(0,0,W,H,'#06111caa');ctx.font='bold 30px monospace';ctx.fillStyle='#c9fff1';ctx.textAlign='center';ctx.fillText('PAUSED',W/2,H/2);ctx.textAlign='left';}ctx.restore();}
const map={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',ArrowUp:'up',KeyZ:'fire',KeyJ:'fire'};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(document.activeElement.tagName)&&state!=='playing'&&state!=='paused')return;if(map[e.code]||['Space','KeyW','ShiftLeft','ShiftRight','KeyX','KeyP','Escape'].includes(e.code))e.preventDefault();if(map[e.code])keys.add(map[e.code]);if(!e.repeat){if(e.code==='Space'||e.code==='KeyW')jumpQueued=true;if(['ShiftLeft','ShiftRight','KeyX'].includes(e.code))dashQueued=true;if(e.code==='KeyP'||e.code==='Escape')pause();}});window.addEventListener('keyup',e=>{if(map[e.code])keys.delete(map[e.code]);});
for(const el of document.querySelectorAll('[data-hold],#jump,#dash')){el.addEventListener('pointerdown',e=>{e.preventDefault();if(state!=='playing')return;el.setPointerCapture(e.pointerId);el.classList.add('pressed');if(el.dataset.hold)held.set(e.pointerId,el.dataset.hold);if(el.id==='jump')jumpQueued=true;if(el.id==='dash')dashQueued=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,e=>{held.delete(e.pointerId);el.classList.remove('pressed');});}
window.addEventListener('blur',()=>{clearInput();if(state==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state==='playing')pause();});$('pause').onclick=pause;$('start').onclick=()=>{if(state==='dead'){score=checkpointScore;kills=checkpointActive?checkpointKills:0;setup(zone,checkpointActive);state='playing';document.body.classList.add('playing');clearInput();}else start();$('start').blur();};$('sound').onclick=()=>{initAudio();muted=!muted;$('sound').textContent=muted?'SOUND OFF':'SOUND ON';tone(660,.1,'sine');};$('auto').onchange=e=>auto=e.target.checked;$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('app').requestFullscreen)await $('app').requestFullscreen();else toast('このブラウザでは端末を横向きにしてください');}catch{toast('端末を横向きにすると広く遊べます');}};
setup(0);$('toast').textContent='';toastTimer=0;let last=performance.now(),acc=0;function loop(now){const elapsed=Math.min(.08,(now-last)/1000);last=now;if(state==='playing'){acc+=elapsed;while(acc>=1/120&&state==='playing'){update(1/120);acc-=1/120;}}else{acc=0;if(state==='title')time+=elapsed;}draw();requestAnimationFrame(loop);}requestAnimationFrame(loop);
})();